### ISSUE TITLE
Print mesg before revolver?

### ISSUE THREAD

**Issue by tmpm697** [molovo/revolver#14]
I don't use mesg with revolver because it gives spalsh as same as the progress bar. I want the text is static. e.g:

```
echo "test" &&  sleep 20 & \
> revolver -i start
```
Here I want `test ⣾`. But revolver keep display on new line, so I get:
```
test
⣾
```

How to have the above expected result?

**Comment by molovo** [comment]
Displaying the message before the icon isn't currently possible, and I have no plans to implement it. Feel free to submit a pull request if this is a feature you'd need

**Comment by tmpm697** [comment]
Is there away to avoid flick/splash mesg in current implementation?
